### ISSUE TITLE
Display more than 5 entries?

### ISSUE THREAD

**Issue by hreality** [stursby/uebersicht-craigslist#2]
How to edit to display more than 5 entries please? Also, can we over ride link color so font is a set color?

**Comment by stursby** [comment]
@hreality Just change the `5` on this line in [app.py](https://github.com/stursby/uebersicht-craigslist/blob/master/craigslist.widget/app.py#L61).

And for the link color, that is all set in the CSS in [craigslist.coffee](https://github.com/stursby/uebersicht-craigslist/blob/master/craigslist.widget/craigslist.coffee#L53).
